version: "3"
services:

  tile38-1:
    image: rashadansari/tile38:1.17.6
    hostname: tile38-1
    container_name: tile38-1
    environment:
      - TILE38_REPLICATION_ENABLED=true
      - REDIS_SENTINEL_HOST=sentinel-1
      - REDIS_SENTINEL_PORT_NUMBER=26379
      - REDIS_SENTINEL_MASTER_NAME=mymaster
    # ports:
    #   - 9851:9851

  tile38-2:
    image: rashadansari/tile38:1.17.6
    hostname: tile38-2
    container_name: tile38-2
    depends_on:
      - tile38-1
      - sentinel-1
      - sentinel-2
      - sentinel-3
    environment:
      - TILE38_REPLICATION_ENABLED=true
      - REDIS_SENTINEL_HOST=sentinel-1
      - REDIS_SENTINEL_PORT_NUMBER=26379
      - REDIS_SENTINEL_MASTER_NAME=mymaster
    # ports:
    #   - 9852:9851

  tile38-3:
    image: rashadansari/tile38:1.17.6
    hostname: tile38-3
    container_name: tile38-3
    depends_on:
      - tile38-1
      - sentinel-1
      - sentinel-2
      - sentinel-3
    environment:
      - TILE38_REPLICATION_ENABLED=true
      - REDIS_SENTINEL_HOST=sentinel-1
      - REDIS_SENTINEL_PORT_NUMBER=26379
      - REDIS_SENTINEL_MASTER_NAME=mymaster
    # ports:
    #   - 9853:9851

  sentinel-1:
    image: bitnami/redis-sentinel:5.0.5
    hostname: sentinel-1
    container_name: sentinel-1
    depends_on:
      - tile38-1
    environment:
      - REDIS_MASTER_HOST=tile38-1
      - REDIS_MASTER_PORT_NUMBER=9851
    # ports:
    #   - 26379:26379

  sentinel-2:
    image: bitnami/redis-sentinel:5.0.5
    hostname: sentinel-2
    container_name: sentinel-2
    depends_on:
      - tile38-1
    environment:
      - REDIS_MASTER_HOST=tile38-1
      - REDIS_MASTER_PORT_NUMBER=9851
    # ports:
    #   - 26380:26379

  sentinel-3:
    image: bitnami/redis-sentinel:5.0.5
    hostname: sentinel-3
    container_name: sentinel-3
    depends_on:
      - tile38-1
    environment:
      - REDIS_MASTER_HOST=tile38-1
      - REDIS_MASTER_PORT_NUMBER=9851
    # ports:
    #   - 26381:26379

  haproxy:
    image: haproxy:1.9.9
    hostname: haproxy
    container_name: haproxy
    depends_on:
      - tile38-1
      - tile38-2
      - tile38-3
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 1986:1986
      - 9851:9851
